"""
Schemi Dati e Costanti per Tenant Registry, Channel Registry e Import Profile Registry.
REF-001 FASE 2A
"""

# PERCORSI FIRESTORE UFFICIALI (Opzione B Validata)
FIRESTORE_SYSTEM_COLLECTION = "system"
FIRESTORE_REGISTRY_DOCUMENT = "registry"
TENANTS_COLLECTION_PATH = "system/registry/tenants"
CHANNELS_COLLECTION_PATH = "system/registry/channels"
IMPORT_PROFILES_COLLECTION_PATH = "system/registry/import_profiles"

# ALLOWLIST DI SICUREZZA PER PARSER STRATEGY
PARSER_STRATEGY_ALLOWLIST = {
    "EXCEL_GENERIC_STRATEGY",
    "PDF_TEXT_STRATEGY",
    "PDF_TABLE_STRATEGY"
}

# ALLOWLIST DI SICUREZZA PER TRASFORMAZIONI CAMPO
TRANSFORMATION_ALLOWLIST = {
    "TRIM",
    "STRIP_UPPER",
    "CLEAN_TEXT",
    "PARSE_INT",
    "PARSE_FLOAT",
    "PARSE_DATE"
}

# ENUM STATI LIFECYCLE IMPORT PROFILE
PROFILE_STATUS_ENUM = {
    "DRAFT",
    "TESTING",
    "APPROVED",
    "ACTIVE",
    "RETIRED"
}

# FILE TYPES AMMESSI
ACCEPTED_FILE_TYPES_ENUM = {
    "PDF",
    "XLSX",
    "XLS",
    "CSV"
}
